# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: push
  #schedule:
    # * is a special character in YAML so you have to quote this string
    # every 5 min
    #- cron:  '*/5 * * * *'


jobs:
  hit-api:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    
    - name: run the script
      #shell: bash
      run: |
        python3 envapiget.py
      env:
        URL: ${{ secrets.url }}
    
